- name: Remove Pacman packages
  community.general.pacman:
    name:
    - kwrite
    state: absent
  become: yes

- name: First setup Arch Linux
  hosts: localhost
  tasks:
  - name: Install Pacman packages
    community.general.pacman:
      name:
      # command line tools
      - git
      - python-pip
      - ffmpeg
      - rsync
      - unrar
      - p7zip
      - man
      - nmap
      - tree
      - tcpdump
      - jq
      - bash-completion
      - rustup
      - base-devel
      - yt-dlp
      # GUI applications 
      - firefox
      - kdeconnect
      - strawberry
      - keepassxc
      - okular
      - filelight
      - partitionmanager
      - kfind
      - steam
      - steam-native-runtime
      - gwenview
      - kcalc
      - vbam-wx
      - dwarffortress
      - qbittorrent
      - krita
      - calibre
      - vlc
      - kiten
      - spectacle
      # Libraries + dependencies
      - gst-plugins-good
      - gst-plugins-bad
      - gst-plugins-ugly
      - gnome-keyring # for minecraft
      - sshfs
      - kdialog
      - kimageformats
      - qt5-imageformats
      - kcm-wacomtablet
      - colord-kde
      - xdg-desktop-portal
      - xdg-desktop-portal-kde
      # Fonts
      - adobe-source-han-sans-jp-fonts
      - adobe-source-han-serif-jp-fonts
      - otf-ipafont
      - ttf-hanazono
      - ttf-sazanami
      - adobe-source-han-sans-kr-fonts
      - ttf-baekmuk
      - noto-fonts-emoji
      - hunspell
      - hunspell-en_gb
      # Wine
      - wine-staging
      - wine-mono
      - wine-gecko
      - winetricks
      state: latest
    become: yes

  # Can't build as it requires user interaction
  # - name: Pull yay
  #   ansible.builtin.git:
  #     repo: https://aur.archlinux.org/yay.git
  #     dest: /tmp/yay
  # - name: Build yay
  #   command: chdir=/tmp/yay makepkg -si

  - name: Create .inputrc
    ansible.builtin.file:
      path: /home/bapanna/.inputrc
      state: touch
      owner: bapanna
      group: bapanna
      mode: '0644'

  - name: Bash case insensitive autocomplete
    ansible.builtin.lineinfile:
      path: "{{ ansible_env.HOME }}/.inputrc"
      state: present
      line: $include /etc/inputrc

  - name: Bash case insensitive autocomplete 2
    ansible.builtin.lineinfile:
      path: "{{ ansible_env.HOME }}/.inputrc"
      state: present
      line: set completion-ignore-case On

  # yay -S minecraft-launcher dropbox spotify hunspell-nb

  - name: Copy wacom scrolling script to user home directory
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/wacom_scrolling.sh"
      dest: "{{ ansible_env.HOME }}"
      owner: "{{ ansible_env.USER }}"
      mode: "+x"

  - name: Copy wacom scrolling desktop file to home directory
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/wacom_scrolling.sh.desktop"
      dest: "{{ ansible_env.HOME }}/.config/autostart/"
      owner: "{{ ansible_env.USER }}"

  - name: Copy wacom tablet configs
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/tabletprofilesrc"
      dest: "{{ ansible_env.HOME }}/.config/"
      owner: "{{ ansible_env.USER }}"

  - name: Copy keyboard shortcuts
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/kglobalshortcutsrc"
      dest: "{{ ansible_env.HOME }}/.config/"
      owner: "{{ ansible_env.USER }}"

  - name: Run wacom scrolling script
    ansible.builtin.command:
      cmd: "{{ ansible_env.HOME }}/wacom_scrolling.sh"
